### PR TITLE
make offline pwa

### PR DESCRIPTION
**Pull request by aeiea**

### CODE REVIEW

**Comment by aeiea** [comment]
pls merge

**Comment by nroutasuo** [comment]
Hi there, thanks for the PR. I am not familiar with this technology and I'm a bit hesitant to merge in code that I don't fully understand myself. I'll look into it, but it might take awhile for this to get merged.

In the meanwhile perhaps you could answer the following:
* What's the benefit of this change?
* How can I test it?
* Does the list of files in pwa-sw.js need to be manually updated when I add new files to the project in the future?

**Comment by aeiea** [comment]
Benefits:
 - The site works offline with no internet
 - The site can be installed as a progressive web app (PWA)
Testing:
 - Go to https://level13-65w.pages.dev
 - Wait around 1 minute
 - Turn off Wi-Fi
 - Close all tabs, then go to https://level13-65w.pages.dev again.
 - It should be available even without Wi-Fi.

**Comment by aeiea** [comment]
I've also added a GitHub action workflow to automatically update the list of files.

**Comment by aeiea** [comment]
i just wasted my morning making a github actions workflow to automatically update the files

**Comment by nroutasuo** [comment]
I finally had a closer look at this now. Thanks the details and the update script. I appreciate the effort put into this and I learned a bunch as well. It all looks good, but I've decided not to merge this now. I think at this stage the maintenance will outweight the benefits. 

However I would like to come back to this later if and when adding better mobile support for the game in general.

**Comment by aeiea** [comment]
kay

**Pull request closed without merging**
