### PR TITLE
Bugfixes for #130 #131 #132

### PR DESCRIPTION
**Pull request by Brilliand**

### CODE REVIEW

**Comment by nroutasuo** [comment]
Thank you for the fixes! They are all neat and seem to work fine. For the itemBonusTypes.movement checks I'd like to come up with some sort of a global "bonus type type" (is decreasing value good? etc) but let's start with fixing the actual problem.

**Comment by Brilliand** [comment]
I did prepare a commit that fixes various non-game-affecting problems with the "movement" bonus type.  I'll upload that for your review.

Here it is: 176886cb8411843faa47c9b5681bb397da92d3ea

Though, that doesn't fix the main problem with movement cost, which is that it's a stat that you want less of, and that's weird.  Could do the same "make a function that returns the type" thing for increasing/decreasing, I suppose.

**Comment by nroutasuo** [comment]
That seems like more exceptions. Perhaps what I really should do is to just change how the stat is represented so that bigger is better like for the rest of them.

**Comment by Brilliand** [comment]
That's definitely a good option.  If you go that route, will you make it subtract or divide?

If it subtracts: That limits the potential for adding movement modifiers for other equipment, since you wouldn't want to allow a movement cost of 0.  (You haven't shown any sign of wanting to add movement modifiers to other equipment, though.)

If it divides: That causes aesthetic problems in the form of numbers with an infinite decimal representation, unless you limit yourself to setting the movement modifiers to certain specific values.

**Comment by nroutasuo** [comment]
Yes I think you are probably right. So far I have no intention of adding movement modifiers to other equipment. I'm currently working on some cheats to make testing easier, but after that I'll look into fixing this at some point. Thanks for the input!

**Pull request merged**
